blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
resources :sessions, only: [:create, :new, :destroy]
resources :users do
  resources :articles do
    resources :comments
  end
end
root 'welcome#index'

end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image
  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

blog/app/models/session.rb
class Session < ApplicationRecord
end

blog/app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, :styles => { :small => "150*150>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :articles, dependent: :destroy 
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def admin?
  	self.admin == 'yes'
  end
  
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :redirect_not_logged_in, only: [:index, :show, :destroy]
  def show
    @article = Article.find(params[:id])
  end
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.create(article_params)
    redirect_to user_path(@user)
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to user_article_path(@article.user, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to user_path(@article.user)
  end
  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "abc", password: "abc", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to user_article_path(@article.user, @article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

blog/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.order('created_at')
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "The photo was added!"
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      log_in user
      user.admin? ? (redirect_to users_path) : (redirect_to user_path(user))
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_not_logged_in, only: [:index, :show, :destroy]
  before_action :admin_user?, only: [:index]

  def index
      @users =User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :address, :admin, :photo)
  end

end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/photos_helper.rb
module PhotosHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
   current_user.present?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def admin_user?
    redirect_to user_path(current_user) unless current_user.admin?    
  end
  
  def redirect_not_logged_in
    redirect_to root_path unless logged_in?
  end

end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_for(@article, url: user_article_path(@article), html: {method: "patch"}) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 

blog/app/views/articles/new.html.erb
<%= form_for :article, url: user_articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', user_articles_path %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<td><%= link_to 'Edit', edit_user_article_path(@article.user,@article) %></td>
<td><%= link_to 'Destroy', user_article_path(@article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article.user,@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

 

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style type="text/css">
    .navbar-header2 {
      float: right;
    }
  </style>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
         <%= link_to "My Blog",root_path , class: "navbar-brand" %>
        </div>
        <div class="navbar-header2">
         <% if logged_in? %>
          <%= link_to "Log out", session_path(current_user), method: :delete %> 
          <% else %>
           <%= link_to "SIGNUP",new_user_path, class: "navbar-brand" %>
           <%= link_to "LOGIN",new_session_path, class: "navbar-brand" %>
          <% end %>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>">
       <%= value %>
     </div>
    <% end %>
      <%= yield %>
  </body>
</html>

blog/app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title %></h4>
  </div>
</div>

blog/app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<%= render @photos %>

blog/app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo do |f| %>
  

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Edit user</h1>
 
<%= form_for @user, :html => { :multipart => true } do |f| %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
  <%= f.label :photo, "Photo" %>
  <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.submit %>
  </p>

 <% end %>

blog/app/views/users/index.html.erb
# <h1>Listing Users</h1>
<table>
  <tr>
    <th>name</th>
    <th>email</th>
    <th colspan="3"></th>
  </tr>
  <% @users.each do |user| %> 
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      </td>
      <td><%= link_to "    Show", user_path(user) %></td>
      <td><%= link_to "    Delete", user_path(user), method: :delete %></td>
      <td colspan="8"></td>
    </tr>
  <% end %>
</table> 

blog/app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :Conformation_password %><br>
    <%= f.password_field :conformation_password %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email</strong>
  <%= @user.email %>
 
</p>

<p>
<%= image_tag @user.photo.url(:small) %>
</p>

<td><%= link_to 'edit', edit_user_path(@user) %></td>
<td><%= link_to 'add article', new_user_article_path(@user) %></td>
 
<h2>Articles</h2>
 <% @user.articles.each do |article| %>
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>
 
  <p>
    <strong>Text:</strong>
    <%= article.text %>
  </p>

  <td><%= link_to 'Show', user_article_path(@user, article) %></td>
<% end %>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%# <%= link_to 'My Blog', controller: 'articles' %>  	